-- =====================================================================
-- 0028 - A mensagem de abertura passa a ser da Psy Comunic.
--
-- O QUE ESTAVA ERRADO
--
-- As 50 mensagens da lista de prospecção diziam "Aqui é o Angelo, da
-- Vettor 28". Marca errada, e pessoa no lugar da empresa: quem fala é
-- a Psy Comunic.
--
-- A oferta também estava curta. Falava em "loja online para vender
-- direto ao cliente final", e o que a Psy entrega é maior: atacado,
-- varejo e aplicativo da marca, numa plataforma que integra
-- marketplaces, ERP e transportadoras.
--
-- O QUE ENTRA NO LUGAR
--
-- Mesma estrutura em todas: quem fala, o gancho daquela marca, a
-- oferta e o convite. O gancho continua sendo o da pesquisa, e é ele
-- que separa abordagem de disparo em massa.
--
-- A OFERTA MUDA COM O QUE A EMPRESA JÁ FAZ, e isso não é enfeite:
--
--   quem só vende no atacado ouve pedido mínimo, tabela por CNPJ e
--   área do lojista, porque loja de varejo não resolve o problema dela;
--
--   quem só vende no varejo não ouve oferta de atacado;
--
--   quem já tem site de atacado e não tem o de varejo (L036) ouve só o
--   que falta, porque oferecer o que a pessoa já comprou é o jeito mais
--   rápido de provar que ninguém olhou o perfil dela.
--
-- Nenhuma coluna muda, nenhum lead é criado ou apagado. Só o texto.
-- =====================================================================

with nova(codigo, mensagem) as (values
  ('L001', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm fabricação própria há mais de 26 anos e 3 lojas em Brusque. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Reiwiu Confecções?'),
  ('L002', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês estão há 26 anos no jeans com loja de fábrica em Brusque. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Peka''s Jeans?'),
  ('L003', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam básicos masculinos e atendem atacado e varejo na FIP. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para YouMen?'),
  ('L004', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm fabricação própria e hoje vendem pelo direct. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Diamond Atacado?'),
  ('L005', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam camisetas e já enviam para todo o Brasil pelo WhatsApp. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Fábrica de Camisetas Brusque?'),
  ('L006', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm uma audiência enorme no plus size com fabricação própria. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Mulher Única?'),
  ('L007', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês trabalham com tricot desde 1980. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Ana Gonçalves Tricot?'),
  ('L008', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm mais de 120 mil seguidores e loja de fábrica de tricot. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Atacadão das Malhas?'),
  ('L009', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam tricot no All Shopping com envio imediato. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para La Miller Tricot?'),
  ('L010', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam fitness e vendem 100% no atacado. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Vida Fit?'),
  ('L011', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam pijamas e já vendem online. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para De Pijama Brusque?'),
  ('L012', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês são fabricantes infantis com mais de 150 mil seguidores atendendo pelo WhatsApp. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Leleco Peteleco?'),
  ('L013', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês produzem infantil e estão na maioria dos estados. A gente refaz a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Pega Mania?'),
  ('L014', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm loja de fábrica fitness vendendo para todo o Brasil. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Iduna Fitness?'),
  ('L015', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês produzem moda íntima direto da fábrica. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Brulini Moda Íntima?'),
  ('L016', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm mais de 20 anos no atacado e selo ABVTEX. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Summer Girl?'),
  ('L017', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês atendem lojistas de plus size no Master Shopping. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Xá Plus?'),
  ('L018', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm quase 120 mil seguidores e coleções exclusivas no atacado. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Alekids?'),
  ('L019', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês atendem lojistas do P ao 16 direto de Gaspar. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Lunedi?'),
  ('L020', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês são uma indústria com 36 anos no infantil. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Rollu?'),
  ('L021', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês vendem bebê a juvenil no atacado e hoje o pedido é por e-mail. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para TMX Kids & Teens?'),
  ('L022', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm confecção infantil própria em Gaspar. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Jidi Kids?'),
  ('L023', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam infantil em Gaspar desde 2003. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Serelepe Kids?'),
  ('L024', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm confecção própria e 64 mil seguidores no atacado infantil. A gente refaz a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para PHO Kids?'),
  ('L025', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês atendem atacado infantil em Gaspar. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para DHC Atacado Infantil?'),
  ('L026', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam infantil e hoje dependem de Mercado Livre, Shein e TikTok. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Vanetex?'),
  ('L027', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm confecção própria em Blumenau. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Lua da Moda Confecções?'),
  ('L028', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês estão começando uma marca fitness com fabricação própria. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para AltSide?'),
  ('L029', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam moda íntima do infantil ao adulto. A gente refaz a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Kunsler?'),
  ('L030', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm confecção própria e 35 mil seguidores. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Maria Guilhermina?'),
  ('L031', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês vendem direto da fábrica no varejo com 37 mil seguidores. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Outlet Arte D''Vestir?'),
  ('L032', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam moda praia e lingerie desde 1991. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Rio Açu?'),
  ('L033', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm 36 anos de moda praia em Ilhota. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Ilhas Rio?'),
  ('L034', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês produzem fitness, lingerie e pijamas desde 2005. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para KSI?'),
  ('L035', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm quase 100 mil seguidores e já exportam. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Julemar Moda Íntima?'),
  ('L036', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês já têm site para atacadista mas não para o consumidor final. A gente monta o que falta: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para HP Moda Íntima?'),
  ('L037', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm mais de 117 mil seguidores e vendem pelo WhatsApp. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Dukali?'),
  ('L038', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês estão desde 1997 com lojas em Ilhota e Brusque. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Diara?'),
  ('L039', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês atendem atacado e varejo de moda íntima. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Atacadão da Moda Íntima (Two)?'),
  ('L040', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm confecção própria com showroom de atacado. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Pamella Nattacha?'),
  ('L041', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês estão desde 1995 com quase 160 mil seguidores. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Camboriú?'),
  ('L042', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam fitness e enviam para o Brasil e exterior. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Divina Forma Fitness?'),
  ('L043', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm confecção própria desde 1991 e 3 lojas em Joinville. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Robsur?'),
  ('L044', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm produção própria há mais de 30 anos. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Dalbelli Confecções?'),
  ('L045', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam calçados no polo de São João Batista. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Ana Jullian Calçados?'),
  ('L046', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês fabricam jeans com 4 lojas e 68 mil seguidores. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Rocksham Jeans?'),
  ('L047', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês têm fabricação própria e 6 lojas físicas. A gente refaz a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Priori?'),
  ('L048', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês vendem do P ao G4 pelo WhatsApp com 4 lojas. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Talinda?'),
  ('L049', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês lançam coleção toda semana e têm mais de 100 mil seguidores. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Atacado de Brusque?'),
  ('L050', 'Oi, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Vi que vocês estão há 15 anos no atacado feminino no Catarina Shopping. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e o que a operação já usa. Faz sentido te mostrar como ficaria para Miss Glamour?'))
update prospeccao p
   set mensagem_abertura = nova.mensagem
  from nova
 where p.codigo = nova.codigo
   and p.mensagem_abertura is distinct from nova.mensagem;
