-- =====================================================================
-- 0031 - A abordagem passa a falar com a PESSOA, e não com a marca.
--
-- O QUE MUDOU NA PRÁTICA
--
-- A mensagem ia para o perfil da marca, onde quem responde é quem cuida
-- da rede social. Agora vai para o Instagram do dono, e o texto precisa
-- se explicar: um estranho no direct pessoal de alguém tem uns dois
-- segundos para dizer por que está ali.
--
-- É isso que a frase nova faz. "Cheguei no seu perfil procurando quem
-- está à frente de X" responde a primeira pergunta que a pessoa faz, e
-- de quebra prova que não é disparo: ninguém procura um nome para mandar
-- mensagem em massa.
--
-- POR QUE O NOME NÃO ESTÁ ESCRITO NO TEXTO
--
-- Ele entra como `{dono}`, e a troca acontece na hora de mostrar e de
-- copiar. O motivo é a ordem das coisas: a mensagem chega pela carga, e
-- o dono é descoberto depois, um a um, pelo CNPJ. Com o nome gravado
-- dentro do texto, cada descoberta exigiria reescrever aquela linha, e
-- quem ainda não tem nome ficaria com a saudação pela metade.
--
--   com nome  "Oi{dono}, tudo bem?" -> "Oi, Mirian, tudo bem?"
--   sem nome  "Oi{dono}, tudo bem?" -> "Oi, tudo bem?"
--
-- A troca mora em `src/lib/dominio/abordagem.ts`, com teste: a
-- pontuação dos dois casos é exatamente onde isso costuma sair errado.
--
-- "de X" E NÃO "da X"
--
-- A lista tem "Atacadão das Malhas", "YouMen" e "Miss Glamour". Artigo
-- definido acerta um gênero e erra o outro, e errar o nome da empresa na
-- primeira linha é pior do que soar formal.
--
-- Só o texto muda. Nenhuma coluna, nenhum lead.
-- =====================================================================

with nova(codigo, mensagem) as (values
  ('L001', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Reiwiu Confecções. Vi que vocês têm fabricação própria há mais de 26 anos e 3 lojas em Brusque. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L002', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Peka''s Jeans. Vi que vocês estão há 26 anos no jeans com loja de fábrica em Brusque. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L003', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de YouMen. Vi que vocês fabricam básicos masculinos e atendem atacado e varejo na FIP. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L004', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Diamond Atacado. Vi que vocês têm fabricação própria e hoje vendem pelo direct. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L005', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Fábrica de Camisetas Brusque. Vi que vocês fabricam camisetas e já enviam para todo o Brasil pelo WhatsApp. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L006', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Mulher Única. Vi que vocês têm uma audiência enorme no plus size com fabricação própria. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L007', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Ana Gonçalves Tricot. Vi que vocês trabalham com tricot desde 1980. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L008', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Atacadão das Malhas. Vi que vocês têm mais de 120 mil seguidores e loja de fábrica de tricot. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L009', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de La Miller Tricot. Vi que vocês fabricam tricot no All Shopping com envio imediato. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L010', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Vida Fit. Vi que vocês fabricam fitness e vendem 100% no atacado. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L011', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de De Pijama Brusque. Vi que vocês fabricam pijamas e já vendem online. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L012', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Leleco Peteleco. Vi que vocês são fabricantes infantis com mais de 150 mil seguidores atendendo pelo WhatsApp. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L013', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Pega Mania. Vi que vocês produzem infantil e estão na maioria dos estados. A gente refaz a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L014', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Iduna Fitness. Vi que vocês têm loja de fábrica fitness vendendo para todo o Brasil. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L015', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Brulini Moda Íntima. Vi que vocês produzem moda íntima direto da fábrica. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L016', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Summer Girl. Vi que vocês têm mais de 20 anos no atacado e selo ABVTEX. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L017', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Xá Plus. Vi que vocês atendem lojistas de plus size no Master Shopping. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L018', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Alekids. Vi que vocês têm quase 120 mil seguidores e coleções exclusivas no atacado. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L019', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Lunedi. Vi que vocês atendem lojistas do P ao 16 direto de Gaspar. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L020', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Rollu. Vi que vocês são uma indústria com 36 anos no infantil. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L021', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de TMX Kids & Teens. Vi que vocês vendem bebê a juvenil no atacado e hoje o pedido é por e-mail. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L022', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Jidi Kids. Vi que vocês têm confecção infantil própria em Gaspar. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L023', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Serelepe Kids. Vi que vocês fabricam infantil em Gaspar desde 2003. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L024', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de PHO Kids. Vi que vocês têm confecção própria e 64 mil seguidores no atacado infantil. A gente refaz a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L025', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de DHC Atacado Infantil. Vi que vocês atendem atacado infantil em Gaspar. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L026', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Vanetex. Vi que vocês fabricam infantil e hoje dependem de Mercado Livre, Shein e TikTok. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L027', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Lua da Moda Confecções. Vi que vocês têm confecção própria em Blumenau. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L028', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de AltSide. Vi que vocês estão começando uma marca fitness com fabricação própria. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L029', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Kunsler. Vi que vocês fabricam moda íntima do infantil ao adulto. A gente refaz a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L030', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Maria Guilhermina. Vi que vocês têm confecção própria e 35 mil seguidores. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L031', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Outlet Arte D''Vestir. Vi que vocês vendem direto da fábrica no varejo com 37 mil seguidores. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L032', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Rio Açu. Vi que vocês fabricam moda praia e lingerie desde 1991. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L033', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Ilhas Rio. Vi que vocês têm 36 anos de moda praia em Ilhota. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L034', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de KSI. Vi que vocês produzem fitness, lingerie e pijamas desde 2005. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L035', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Julemar Moda Íntima. Vi que vocês têm quase 100 mil seguidores e já exportam. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L036', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de HP Moda Íntima. Vi que vocês já têm site para atacadista mas não para o consumidor final. A gente monta o que falta: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L037', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Dukali. Vi que vocês têm mais de 117 mil seguidores e vendem pelo WhatsApp. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L038', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Diara. Vi que vocês estão desde 1997 com lojas em Ilhota e Brusque. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L039', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Atacadão da Moda Íntima (Two). Vi que vocês atendem atacado e varejo de moda íntima. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L040', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Pamella Nattacha. Vi que vocês têm confecção própria com showroom de atacado. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L041', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Camboriú. Vi que vocês estão desde 1995 com quase 160 mil seguidores. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L042', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Divina Forma Fitness. Vi que vocês fabricam fitness e enviam para o Brasil e exterior. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L043', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Robsur. Vi que vocês têm confecção própria desde 1991 e 3 lojas em Joinville. A gente monta a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L044', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Dalbelli Confecções. Vi que vocês têm produção própria há mais de 30 anos. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L045', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Ana Jullian Calçados. Vi que vocês fabricam calçados no polo de São João Batista. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L046', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Rocksham Jeans. Vi que vocês fabricam jeans com 4 lojas e 68 mil seguidores. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L047', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Priori. Vi que vocês têm fabricação própria e 6 lojas físicas. A gente refaz a operação inteira: a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L048', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Talinda. Vi que vocês vendem do P ao G4 pelo WhatsApp com 4 lojas. A gente monta a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L049', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Atacado de Brusque. Vi que vocês lançam coleção toda semana e têm mais de 100 mil seguidores. A gente refaz a operação inteira: a loja de atacado, a loja de varejo e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'),
  ('L050', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Miss Glamour. Vi que vocês estão há 15 anos no atacado feminino no Catarina Shopping. A gente monta a operação inteira: a loja de atacado com pedido mínimo, tabela por CNPJ e área do lojista, e o aplicativo da marca, numa plataforma que integra marketplaces, ERP, transportadoras e mais. Faz sentido te mostrar como ficaria?'))
update prospeccao p
   set mensagem_abertura = nova.mensagem
  from nova
 where p.codigo = nova.codigo
   and p.mensagem_abertura is distinct from nova.mensagem;

/* O canal já era esse nas 50, e agora é regra: toda abordagem desta
   lista acontece no Instagram. Escrito no banco para a tela não ter de
   supor. */
update prospeccao set canal = 'Instagram DM' where canal is distinct from 'Instagram DM';
