-- =====================================================================
-- 0032 - A abordagem passa a carregar a credencial do site.
--
-- O QUE FALTAVA
--
-- A mensagem se apresentava por adjetivo ("especialistas em criação de
-- marcas de sucesso") e parava aí. O site inteiro faz o contrário: ele
-- se apoia num fato que um concorrente não copia sem mentir, e é o
-- primeiro cartão de `credenciais`, em `src/conteudo/marca.ts`.
--
-- Uma fábrica de moda recebe dez mensagens de agência por semana. O que
-- separa a décima primeira das outras dez não é o adjetivo. É a linha
-- que a pessoa não consegue escrever se não for verdade.
--
-- AS TRÊS COISAS QUE ENTRARAM, E DE ONDE VIERAM
--
--   `marca.posicionamento`  "Não uma agência de mídia" vira "Não somos
--                           agência de mídia", que é a primeira coisa a
--                           dizer para quem já foi queimado por uma.
--
--   `credenciais[01]`       "quem conduz a operação foi sócio de um
--                           e-commerce de R$ 17 milhões por ano". O
--                           número é o de `faturamento.ano`, escrito
--                           exatamente como o site escreve: "milhões"
--                           solto ou "R$ 17 mi" seriam a mesma
--                           afirmação com outro peso.
--
--   `jornada`               "seguimos tocando todo mês depois do
--                           lançamento" responde o "e depois?", que é a
--                           objeção de quem já ficou com um site pronto
--                           e ninguém para cuidar.
--
-- E o convite passa a ser o CTA do site: diagnóstico gratuito. "Posso
-- te mostrar" pede atenção; "faço um diagnóstico" entrega algo antes de
-- pedir qualquer coisa.
--
-- O TAMANHO FOI MEDIDO, E CUSTOU
--
-- De 75 para 105 palavras em média. A primeira versão com a credencial
-- tinha 126, e foi cortada: saíram "então aqui se fala de faturamento,
-- e não de clique", "área do lojista" e metade do convite. O que
-- sobrou é o que não dá para tirar sem a mensagem voltar a ser
-- adjetivo.
--
-- Nenhuma coluna muda. `{dono}` continua sendo trocado na hora de
-- copiar, por `src/lib/dominio/abordagem.ts`.
-- =====================================================================

with nova(codigo, mensagem) as (values
  ('L001', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Reiwiu Confecções. Vi que vocês têm fabricação própria há mais de 26 anos e 3 lojas em Brusque. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L002', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Peka''s Jeans. Vi que vocês estão há 26 anos no jeans com loja de fábrica em Brusque. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L003', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de YouMen. Vi que vocês fabricam básicos masculinos e atendem atacado e varejo na FIP. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L004', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Diamond Atacado. Vi que vocês têm fabricação própria e hoje vendem pelo direct. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L005', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Fábrica de Camisetas Brusque. Vi que vocês fabricam camisetas e já enviam para todo o Brasil pelo WhatsApp. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L006', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Mulher Única. Vi que vocês têm uma audiência enorme no plus size com fabricação própria. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L007', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Ana Gonçalves Tricot. Vi que vocês trabalham com tricot desde 1980. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L008', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Atacadão das Malhas. Vi que vocês têm mais de 120 mil seguidores e loja de fábrica de tricot. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L009', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de La Miller Tricot. Vi que vocês fabricam tricot no All Shopping com envio imediato. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L010', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Vida Fit. Vi que vocês fabricam fitness e vendem 100% no atacado. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L011', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de De Pijama Brusque. Vi que vocês fabricam pijamas e já vendem online. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L012', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Leleco Peteleco. Vi que vocês são fabricantes infantis com mais de 150 mil seguidores atendendo pelo WhatsApp. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L013', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Pega Mania. Vi que vocês produzem infantil e estão na maioria dos estados. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L014', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Iduna Fitness. Vi que vocês têm loja de fábrica fitness vendendo para todo o Brasil. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L015', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Brulini Moda Íntima. Vi que vocês produzem moda íntima direto da fábrica. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L016', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Summer Girl. Vi que vocês têm mais de 20 anos no atacado e selo ABVTEX. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L017', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Xá Plus. Vi que vocês atendem lojistas de plus size no Master Shopping. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L018', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Alekids. Vi que vocês têm quase 120 mil seguidores e coleções exclusivas no atacado. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L019', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Lunedi. Vi que vocês atendem lojistas do P ao 16 direto de Gaspar. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L020', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Rollu. Vi que vocês são uma indústria com 36 anos no infantil. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L021', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de TMX Kids & Teens. Vi que vocês vendem bebê a juvenil no atacado e hoje o pedido é por e-mail. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L022', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Jidi Kids. Vi que vocês têm confecção infantil própria em Gaspar. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L023', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Serelepe Kids. Vi que vocês fabricam infantil em Gaspar desde 2003. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L024', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de PHO Kids. Vi que vocês têm confecção própria e 64 mil seguidores no atacado infantil. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L025', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de DHC Atacado Infantil. Vi que vocês atendem atacado infantil em Gaspar. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L026', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Vanetex. Vi que vocês fabricam infantil e hoje dependem de Mercado Livre, Shein e TikTok. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L027', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Lua da Moda Confecções. Vi que vocês têm confecção própria em Blumenau. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L028', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de AltSide. Vi que vocês estão começando uma marca fitness com fabricação própria. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L029', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Kunsler. Vi que vocês fabricam moda íntima do infantil ao adulto. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L030', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Maria Guilhermina. Vi que vocês têm confecção própria e 35 mil seguidores. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L031', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Outlet Arte D''Vestir. Vi que vocês vendem direto da fábrica no varejo com 37 mil seguidores. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L032', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Rio Açu. Vi que vocês fabricam moda praia e lingerie desde 1991. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L033', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Ilhas Rio. Vi que vocês têm 36 anos de moda praia em Ilhota. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L034', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de KSI. Vi que vocês produzem fitness, lingerie e pijamas desde 2005. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L035', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Julemar Moda Íntima. Vi que vocês têm quase 100 mil seguidores e já exportam. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L036', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de HP Moda Íntima. Vi que vocês já têm site para atacadista mas não para o consumidor final. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta o que falta: a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L037', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Dukali. Vi que vocês têm mais de 117 mil seguidores e vendem pelo WhatsApp. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L038', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Diara. Vi que vocês estão desde 1997 com lojas em Ilhota e Brusque. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L039', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Atacadão da Moda Íntima (Two). Vi que vocês atendem atacado e varejo de moda íntima. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L040', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Pamella Nattacha. Vi que vocês têm confecção própria com showroom de atacado. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L041', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Camboriú. Vi que vocês estão desde 1995 com quase 160 mil seguidores. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L042', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Divina Forma Fitness. Vi que vocês fabricam fitness e enviam para o Brasil e exterior. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L043', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Robsur. Vi que vocês têm confecção própria desde 1991 e 3 lojas em Joinville. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L044', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Dalbelli Confecções. Vi que vocês têm produção própria há mais de 30 anos. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L045', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Ana Jullian Calçados. Vi que vocês fabricam calçados no polo de São João Batista. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L046', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Rocksham Jeans. Vi que vocês fabricam jeans com 4 lojas e 68 mil seguidores. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L047', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Priori. Vi que vocês têm fabricação própria e 6 lojas físicas. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L048', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Talinda. Vi que vocês vendem do P ao G4 pelo WhatsApp com 4 lojas. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L049', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Atacado de Brusque. Vi que vocês lançam coleção toda semana e têm mais de 100 mil seguidores. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente refaz a loja de atacado, a loja de varejo e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'),
  ('L050', 'Oi{dono}, tudo bem? Aqui é da Psy Comunic, especialistas em criação de marcas de sucesso. Cheguei no seu perfil procurando quem está à frente de Miss Glamour. Vi que vocês estão há 15 anos no atacado feminino no Catarina Shopping. Não somos agência de mídia: quem conduz a operação foi sócio de um e-commerce de R$ 17 milhões por ano. A gente monta a loja de atacado com pedido mínimo e tabela por CNPJ, e o aplicativo da marca, com marketplaces, ERP e transportadoras integrados, e seguimos tocando todo mês depois do lançamento. Faz sentido eu fazer um diagnóstico gratuito e te mostrar o que dá para melhorar?'))
update prospeccao p
   set mensagem_abertura = nova.mensagem
  from nova
 where p.codigo = nova.codigo
   and p.mensagem_abertura is distinct from nova.mensagem;

-- ---------------------------------------------------------------------
-- A segunda mensagem perde o pedágio.
--
-- Ela começava com "Posso te perguntar uma coisa?". Como PRIMEIRA
-- mensagem aquilo pedia licença antes de tomar o tempo de um estranho.
-- Agora ela vem depois de uma abertura de cem palavras, para alguém que
-- já leu e não respondeu: pedir licença de novo é uma frase inteira
-- gasta para não perguntar nada.
--
-- O `trim` cobre o espaço que sobra, e o `like` garante que só as que
-- realmente têm o pedágio sejam tocadas.
-- ---------------------------------------------------------------------
update prospeccao
   set pergunta_seguinte = initcap(left(btrim(replace(pergunta_seguinte, 'Posso te perguntar uma coisa?', '')), 1))
                           || substr(btrim(replace(pergunta_seguinte, 'Posso te perguntar uma coisa?', '')), 2)
 where pergunta_seguinte like 'Posso te perguntar uma coisa?%';
